github_username: mondyjosh
ssh_key: "~/.ssh/id_ed25519"

minimum_roles:
  - system
  - fastfetch
  - fonts
  - git
  - lazygit
  - neovim
  - wezterm
  - zsh
  - gh

workstation_roles:
  - firefox
  - onedrive
  - sway
  - tmux
  - vscodium
  - zoom
  # - dotnet # TODO
  # - flameshot # TODO: Use package instead of Flatpak
  # - gimp # TODO: Use package instead of Flatpak
  # - golang # TODO
  # - kdenlive # TODO: Use package instead of Flatpak
  # - keepassxc # TODO: Use package instead of Flatpak
  # - node # TODO
  # - obsidian  # TODO: Use package instead of Flatpak # TODO: Consider logseq as FOSS alternative
  # - postman # TODO: Use package instead of Flatpak # TODO: Find TUI FOSS alternative
  # - rust # TODO
  # - slack # TODO: Use package instead of Flatpak
  # - spotify # TODO: Use package instead of Flatpak
  # - thunderbird # TODO: Use package instead of Flatpak
  # - wireshark # TODO: Use package instead of Flatpak

playstation_roles:
  - mangohud
  # - audacity # TODO
  # - discord # TODO: Use package instead of Flatpak
  # - phoronix # TODO (don't forget to install PHP)
  # - signal
  # - steam # TODO: Use package instead of Flatpak

