#!/usr/bin/env bash

## WARNING #############################
# This is copied straight from Primagen,
# who developed it on Debian systems.
# YMMV
########################################

# Undo node
npm uninstall -g yarn typescript-language-server typescript
sudo dnf remove nodejs npm
rm /usr/local/lib/node_modules/n/bin/n
rm /usr/local/bin/n
rm /usr/local/bin/node

# Undo zsh
uninstall_oh_my_zsh
chsh /bin/bash
sudo dnf remove zsh

# Undo Slack
sudo dnf remove slack-desktop

# Undo Core Install
sudo dnf remove curl htop stow tmux buildessential wireshark golang fzf lsof kdenlive i3 gimp ccache ninja-build yarn python3-pip xclip slack dconf-editor nvidia-settings pavucontrol clangd screenkey lua tldr
