#!/usr/bin/env bash

# What is the difference between this and ansible-run?

# Install ansible
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

# install community.general
ansible-galaxy collection install community.general

