- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags: 
        - node
        - zsh
  tasks: 
  - import_tasks: tasks/i3-setup.yml
  - import_tasks: tasks/node-setup.yml
  - import_tasks: tasks/zsh-setup.yml
  
