- name: "Workstation Setup - mondyjosh"
  hosts: localhost
  connection: local

  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi passphrase (ignore if chezmoi is already installed)
      private: true

    - name: include_playstation_roles
      prompt: Include playstation roles [yes/no]

  pre_tasks:
    - name: "Execute Pre-Tasks"
      ansible.builtin.include_tasks: pre_tasks/main.yml

  tasks:
    - name: "Set roles - {{ include_playstation_roles|bool | ternary('🕹️ Play Mode', '👔 Business Mode ') }}"
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or include_playstation_roles|bool | ternary(workstation_roles + playstation_roles, workstation_roles)  | difference(exclude_roles | default([])) }}"
      tags:
        - always
        - workstation

    - name: "Display roles"
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always
        - workstation

    - name: "Run roles"
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
        - workstation
