#!/usr/bin/env bash

# Run local workstation install
# TODO: Rename main.yml to workstation-specific (work, personal, dev-only, etc)
# TODO: Add -K flag to ansible.cfg (sudo prompt)
ansible-playbook main.yml -K

# TODO: Add separate commands for role subsets (dev,  office stuff like zoom, firefox, etc., play stuff like steam, mangohud)
## Playstation (install steam, etc.)
# ansible-playbook main.yml -e playstation
