#!/usr/bin/env bash

#if [[ $(whoami) != "root" ]]; then
#    echo "Please run this script with sudo:"
#    echo "sudo $0 $*"
#    exit 1
#fi

# Run local developer workstation install
ansible-playbook main.yml -i inventories/localhost.ini -K # -vvv # for debug messages
