- name: Install productivity packages
  become: true
  apt:
    name:
      - tmux
      - wireshark
      - fzf
      - fd
      - kdenlive
      - gimp
      - xclip
      - screenkey
      - tldr
      - ripgrep
      - shutter
  tags:
    - install
    - productivity

