- name: Install Zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell to Zsh
  shell: chsh -s $(which zsh)
  tags: 
    - zsh
# This will fall over if oh-my-zsh is already installed on the machine
# TODO: add check and handle scenario when oh-my-zsh is already installed
#- name: Install oh-my-zsh
#  shell: >-
#    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#  tags:
#    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags:
    - zsh
- name: Install powerline10k theme
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    depth: 1
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
  tags:
    - zsh

