- name: Install Zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell to Zsh
  shell: chsh -s $(which zsh)
  tags: 
    - zsh
- name: Install oh-my-zsh if not existing
  shell: >-
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    chdir: /opt
    creates: ~/.oh-my-zsh
  tags:
    - zsh
    - oh-my-zsh
- name: Install oh-my-zsh plugin - zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - zsh
    - oh-my-zsh
    - plugins
- name: Install oh-my-zsh plugin - zsh-nvm plugin
  ansible.builtin.git:
    repo: 'https://github.com/lukechilds/zsh-nvm'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-nvm
  tags:
    - zsh
    - oh-my-zsh
    - plugins
- name: Install oh-my-zsh theme - powerline10k 
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    depth: 1
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
  tags:
    - zsh
    - oh-my-zsh
    - themes
