# original order
# TODO: Break up dependencies so stuff can run unordered
#     - import_tasks: tasks/core-setup.yml
#     - import_tasks: tasks/flatpaks.yml
#     - import_tasks: tasks/node-setup.yml
#     - import_tasks: tasks/nvim-setup.yml
#     - import_tasks: tasks/productivity-tools.yml
#     - import_tasks: tasks/zsh-setup.yml

#- name: Install Core Setup
#  ansible.builtin.include_tasks: tasks/core-setup.yml
#  args:
#    apply:
#      tags:
#        - install
#        - config
#        - nvim
#  tags:
#    - always

#- name: Install/Configure Neovim
#  ansible.builtin.include_tasks: tasks/nvim-setup.yml
#  args:
#    apply:
#      tags:
#        - install
#        - config
#        - nvim
#  tags:
#    - always

# - name: Install/Configure Zsh | {{ ansible_distribution }} |
#  ansible.builtin.include_tasks: tasks/zsh-setup.yml
#  args:
#    apply:
#      tags:
#        - install
#        - config
#        - zsh
#  tags:
#    - always

