- name: "VSCodium | Fedora | Add VSCodium RPM repo"
  become: true
  copy:
    dest: /etc/yum.repos.d/vscodium.repo
    mode: '0644'
    content: |
      [gitlab.com_paulcarroty_vscodium_repo]
      name=gitlab.com_paulcarroty_vscodium_repo
      baseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey={{ vscodium_gpg_key_url }}
      metadata_expire=1h
  tags:
    - install
    - vscodium

# If you want vscodium-insiders, then replace codium by codium-insiders
- name: "VSCodium | Fedora | Install VSCodium"
  become: true
  dnf:
    name: codium
    state: latest
  tags:
    - install
    - vscodium
