- name: "VSCodium | Ubuntu | Download VSCodium GPG key and convert to keyring"
  shell: |
    wget -qO - {{ vscodium_gpg_key_url }} \
      | gpg --dearmor > {{ vscodium_keyring_path }}
  args:
    creates: "{{ vscodium_keyring_path }}"
  tags:
    - install
    - vscodium

- name: "VSCodium | Ubuntu | Add VSCodium repo"
  become: true
  copy:
    dest: /etc/apt/sources.list.d/vscodium.sources
    mode: '0644'
    content: |
      Types: deb
      URIs: https://download.vscodium.com/debs
      Suites: vscodium
      Components: main
      Architectures: amd64 arm64
      Signed-By: {{ vscodium_keyring_path }}
  tags:
    - install
    - vscodium

- name: "VSCodium | Ubuntu | Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - install
    - vscodium

# If you want vscodium-insiders, then replace codium by codium-insiders
- name: "VSCodium | Ubuntu | Install VSCodium"
  become: true
  ansible.builtin.apt:
    name: codium
    state: latest
  tags:
    - install
    - vscodium
