- name: "Lazygit | Fedora | Enable Copr repo"
  community.general.copr:
    name: atim/lazygit
    state: enabled
  tags:
    - lazygit
    - install

- name: "Lazygit | Fedora | Install lazygit"
  ansible.builtin.dnf:
    name:
      - lazygit
    state: present
  become: true
  tags:
    - lazygit
    - install
