- name: "Lazygit | Fedora | Enable Copr"
  shell: sudo dnf copr enable atim/lazygit -y
  tags:
    - lazygit
    - install

- name: "Lazygit | Fedora | Install lazygit"
  ansible.builtin.dnf:
    name:
      - lazygit
    state: present
  become: true
  tags:
    - lazygit
    - install
