#- name: "NVIDIA | {{ ansible_distribution }} | Install NVIDIA Drivers"
#  become: true
#  ansible.builtin.dnf:
#    name:
#    state: present
#  tags:
#    - drivers
#    - install
#    - nvidia

# TODO: Implement https://phoenixnap.com/kb/fedora-nvidia-drivers

# STEP 1 - Install Repository (free RPM repository)
# ------------------------------------------------------------------------------
# - For free repositories, use:
# sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
# - For non-free repositories, use:
# sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# STEP 2 - Detect Nvidia Card
# ------------------------------------------------------------------------------
# lspci | grep VGA
# --
# expected output:
#   ~$ lspci | grep VGA
#   01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)

# STEP 3 - Install Nvidia Drivers
# ------------------------------------------------------------------------------
# - Depending on your GPU model, use the appropriate command to install corresponding Nvidia drivers.
# - For current GeForce/Quadro/Tesla models, use:
#   sudo dnf install akmod-nvidia
# - For legacy drivers for GeForce 400/500 models, use:
#   sudo dnf install xorg-x11-drv-nvidia-390xx akmod-nvidia-390xx
# - For legacy drivers for GeForce 8/9/200/300 models, use:
#   sudo dnf install xorg-x11-drv-nvidia-340xx akmod-nvidia-340xx
# When prompted, type Y and press Enter to confirm the installation.

# STEP 4 - Reboot

