- name: "ssh | Ensure .ssh directory exists"
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: "ssh | Install ssh key"
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: "ssh | Install ssh public key"
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: "ssh | Set authorized key taken from file"
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ ssh_dir }}/id_rsa.pub"
  with_fileglob:
  - "{{ ssh_dir }}/*.pub"
