# TODO: Audit list to see if packages are relevant to my workflow
- name: "System | {{ ansible_distribution }} | Install System Packages"
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - ccache
      - clang
      - clangd
      - cmake
      - compton
      - curl
      - dconf-editor
      - gettext
      - golang
      - htop
      - i3
      - libpthread-stubs0-dev
      - libtool
      - libtool-bin
      - lsof
      - lua5.1
      - moreutils
      - ninja-build
      - nvidia-settings
      - pavucontrol
      - pkg-config
      - python3-pip
      - ubuntu-mate-desktop
      - unzip
  tags:
    - install
    - system

# TODO: Audit list to see if packages are relevant to my workflow
- name: "System | {{ ansible_distribution }} | Install Productivity Tools"
  become: true
  ansible.builtin.apt:
    name:
      - fd-find
      - fzf
      - ripgrep
      - tldr
      - tmux # TODO: Should TMUX get its own role?
      - xclip
  tags:
    - install
    - productivity
    - system
