- name: "Zsh | Remove oh-my-zsh Plugins and Themes"
  shell: rm -rf ~/.oh-my-zsh/custom/plugins/* ~/.oh-my-zsh/custom/themes/*
  become: true
  tags:
    - cleanup
    - zsh
    - oh_my_zsh

- name: "Zsh | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: zsh_distribution_config
  tags:
    - zsh

- name: "Zsh | {{ansible_distribution}} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: zsh_distribution_config.stat.exists
  tags:
    - zsh
    - install

- name: "Zsh | Set Zsh as Default Shell for Users"
  shell: chsh -s /bin/zsh
  become: true
  tags:
    - zsh

- name: "Zsh | Install Oh-My-Zsh"
  shell: >-
    sh -c "$(curl -fsSL
    https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    chdir: /opt
    creates: ~/.oh-my-zsh
  tags:
    - zsh
    - oh_my_zsh

- name: "Zsh | Install oh-my-zsh Plugin - zsh-autosuggestions"
  ansible.builtin.git:
    repo: "git@github.com:zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    key_file: "{{ ssh_key}}"
    update: true
  tags:
    - zsh
    - oh_my_zsh
    - plugins

- name: "Zsh | Install oh-my-zsh plugin - zsh-nvm plugin"
  ansible.builtin.git:
    repo: "git@github.com:lukechilds/zsh-nvm.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-nvm"
    key_file: "{{ ssh_key}}"
    update: true
  tags:
    - zsh
    - oh_my_zsh
    - plugins

- name: "Zsh | Install oh-my-zsh Theme - Spaceship"
  ansible.builtin.git:
    repo: "git@github.com:spaceship-prompt/spaceship-prompt.git"
    dest: "~/.oh-my-zsh/custom/themes/spaceship-prompt"
    key_file: "{{ ssh_key}}"
    update: true
    depth: 1
  tags:
    - zsh
    - oh-my-zsh
    - themes
