- name: "OneDrive | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: onedrive_config
  tags:
    - onedrive

- name: "OneDrive | {{ ansible_distribution }} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: onedrive_config.stat.exists
  tags:
    - install
    - onedrive
