- name: "Spotify | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: spotify_distribution_config
  tags:
    - spotify

- name: "Spotify | {{ansible_distribution}} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: spotify_distribution_config.stat.exists
  tags:
    - spotify
    - install

