- name: "gh | Ubuntu | Add GitHub CLI GPG key"
  ansible.builtin.get_url:
    url: "{{ gh_gpg_key_url }}"
    dest: "{{ gh_keyring_path }}"
    mode: "0644"
  tags:
    - gh
    - install

- name: "gh | Ubuntu | Add GitHub CLI APT repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ gh_keyring_path }}] https://cli.github.com/packages stable main"
    state: present
    filename: github-cli
  tags:
    - gh
    - install

- name: "gh | Ubuntu | Install GitHub CLI"
  ansible.builtin.apt:
    name: gh
    update_cache: yes
    state: present
  tags:
    - gh
    - install
