- name: "Git | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: git_distribution_config
  tags:
    - git

- name: "Git | {{ansible_distribution}} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: git_distribution_config.stat.exists
  tags:
    - git
    - install

