- name: "WezTerm | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: wezterm_config
  tags:
    - wezterm

- name: "WezTerm | {{ ansible_distribution }} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: wezterm_config.stat.exists
  tags:
    - install
    - wezterm
