- name: "fastfetch | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: fastfetch_config
  tags:
    - fastfetch

- name: "fastfetch | {{ ansible_distribution }} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: fastfetch_config.stat.exists
  tags:
    - install
    - fastfetch
