- name: "fastfetch | {{ ansible_distribution }} | Add fastfetch PPA"
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:zhangsongcui3371/fastfetch

- name: "fastfetch | {{ ansible_distribution }} | Install fastfetch"
  become: true
  ansible.builtin.apt:
    name:
      - fastfetch
  tags:
    - install
    - fastfetch
