- name: "Pre-Tasks | {{ ansible_distribution }} | Update Cache"
  ansible.builtin.dnf:
    update_cache: true
  become: true
  tags:
    - system

- name: "Flatpak | {{ ansible_distribution }} | Flatpak - Flatpak"
  ansible.builtin.dnf:
    name: flatpak
    state: present
  become: true
  tags:
    - install
    - flatpak

