- name: "Pre-Tasks | Fedora | Enable Copr plugin"
  become: true
  dnf:
    name: dnf-plugins-core
    state: present

- name: "Pre-Tasks | Fedora | Update Cache"
  become: true
  ansible.builtin.dnf:
    update_cache: true
  tags:
    - system
