- name: "Pre-Tasks | Fedora | Enable Copr plugin"
  become: true
  dnf:
    name: dnf-plugins-core
    state: present
  tags:
    - system

- name: "Pre-Tasks | Fedora | Enable RPM Fusion Free Repo"
  become: true
  ansible.builtin.dnf:
    name: >
      https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  tags:
    - system

- name: "Pre-Tasks | Fedora | Enable RPM Fusion Nonfree Repo"
  become: true
  ansible.builtin.dnf:
    name: >
      https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  tags:
    - system

- name: "Pre-Tasks | Fedora | Update Cache"
  become: true
  ansible.builtin.dnf:
    update_cache: true
  tags:
    - system