- name: "Pre-Tasks | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "pre_tasks/{{ ansible_distribution }}.yml"
  register: pre_tasks_distribution_config
  tags: [pre-tasks]

- name: "Pre-Tasks | {{ansible_distribution}} | Install Dependencies"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: pre_tasks_distribution_config.stat.exists
  tags: [pre-tasks]
# TODO: disable for some troubleshooting
# - name: "SSH | Add SSH Key to SSH Agent"
#   shell: ssh-add ~/.ssh/id_ed25519
#   tags:[pre-tasks]
