# TODO: Ensure community.general is installed from ansible-galaxy
# TODO: Ensure chezmoi is installed and ready
# TODO: Establish must_haves prior to executing any roles

- name: "Pre-Tasks | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "pre_tasks/tasks/{{ ansible_distribution }}.yml"
  register: git_distribution_config
  tags:
    - pre-tasks

- name: "Pre-Tasks | {{ansible_distribution}} | Install Dependencies"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: git_distribution_config.stat.exists
  tags:
    - pre-tasks
