# TODO: Ensure community.general is installed from ansible-galaxy
# TODO: Ensure chezmoi is installed and ready
# TODO: Establish must_haves prior to executing any roles

- name: "Pre-Tasks | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "pre_tasks/{{ ansible_distribution }}.yml"
  register: pre_tasks_distribution_config
  tags:
    - pre-tasks

- name: "Pre-Tasks | {{ansible_distribution}} | Install Dependencies"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: pre_tasks_distribution_config.stat.exists
  tags:
    - pre-tasks

- name: "Flatpak | Add Flathub Repository"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
    - flathub
    - repos

- name: "Flatpak | Install Builder"
  community.general.flatpak:
    name: org.flatpak.Builder
    state: present
  tags:
    - builder
    - flatpak
    - install
