- name: "Alacritty | Check if cargo Is Installed"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - install
    - rust

- name: "Alacritty | Download Installer"
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - install
    - rust

- name: "Alacritty | Install Rust/cargo"
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - install
    - rust

# For now, I'm just interested in the Alacritty binary; install via cargo
- name: "Alacritty | Install alacritty"
  when: cargo_exists is failed
  shell: cargo install alacritty
  tags:
    - alacritty
    - cargo
    - rust
