- name: "NVIDIA | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: nvidia_config
  tags:
    - nvidia

- name: "NVIDIA | {{ ansible_distribution }} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: nvidia_config.stat.exists
  tags:
    - install
    - nvidia
