- name: "Neovim | Fedora | Install Build Dependencies"
  become: true
  ansible.builtin.dnf:
    name:
      - ninja-build
      - cmake
      - gcc
      - make
      - unzip
      - gettext
      - curl
      - glibc-gconv-extra
    state: present
  tags:
    - install
    - neovim

- name: "Neovim | Fedora | Install LazyVim Dependencies"
  become: true
  ansible.builtin.dnf:
    name:
      - ripgrep
      - fd-find
      - fzf
      - git
      # - lazygit
  tags:
    - install
    - neovim
    - neovim_lazyvim

- name: "Neovim | Fedora | Install Plugin Development Dependencies"
  become: true
  ansible.builtin.dnf:
    name: luarocks
  tags:
    - install
    - lua
    - neovim
    - neovim_plugins
