- name: "Neovim | {{ ansible_distribution }} | Install Build Prerequisites"
  ansible.builtin.dnf:
    name:
      - ninja-build
      - cmake
      - gcc
      - make
      - unzip
      - gettext
      - curl
      - glibc-gconv-extra
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | LazyVim - Install Prerequisites"
  become: true
  ansible.builtin.dnf:
    name:
      - ripgrep
      - fd-find
      - git
  tags:
    - neovim_lazyvim

- name: "Neovim | {{ ansible_distribution }} | Plugin Development - Install LuaRocks"
  become: true
  ansible.builtin.dnf:
    name: luarocks
  tags:
    - neovim_plugins
    - lua
