- name: "Neovim | Set Distribution Config: {{ ansible_distribution }} |"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config
  tags:
    - neovim

- name: "Neovim | {{ansible_distribution}} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists
  tags:
    - neovim
    - install
