- name: "Neovim | Set Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config
  tags:
    - neovim

- name: "Neovim | {{ansible_distribution}} | Run Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists
  tags:
    - install
    - neovim

- name: "Neovim | Clone stable branch"
  ansible.builtin.git:
    repo: "git@github.com:neovim/neovim.git"
    dest: "{{ neovim_dir }}"
    key_file: "{{ ssh_key | expanduser }}"
    version: "stable"
    update: true
    force: true
    refspec: "+refs/tags/*:refs/tags/*"
  register: git_result
  tags:
    - install
    - neovim

- name: "Neovim | Get stable branch HEAD SHA"
  command: git rev-parse HEAD
  args:
    chdir: "{{ neovim_dir }}"
  register: current_sha
  changed_when: false
  tags:
    - install
    - neovim

- name: "Neovim | Init last_sha to empty"
  set_fact:
    last_sha: ""
  no_log: true
  tags:
    - install
    - neovim

- name: "Neovim | Check for last build SHA file"
  stat:
    path: "{{ neovim_last_sha_file }}"
  register: sha_file
  tags:
    - install
    - neovim

- name: "Neovim | Read last build SHA"
  ansible.builtin.slurp:
    src: "{{ neovim_dir }}/.neovim_build_sha"
  register: last_sha_file
  when: sha_file.stat.exists
  tags:
    - install
    - neovim

- name: "Neovim | Set fact: last build SHA"
  set_fact:
    last_sha: "{{ last_sha_file.content | b64decode | trim }}" 
  when: last_sha_file is defined and ('content' in last_sha_file)
  tags:
    - install
    - neovim

# If the stable branch's HEAD SHA has changed, time for a new build
- name: "Neovim | Build stable with Debug Info"
  become: true
  shell: "make CMAKE_BUILD_TYPE=RelWithDebInfo"
  args:
    chdir: "{{ neovim_dir }}"
  when: last_sha != current_sha.stdout
  tags:
    - install
    - neovim

# If the stable branch's HEAD SHA has changed, install new build 
- name: "Neovim | Install new stable build"
  become: true
  shell: "make install"
  args:
    chdir: "{{ neovim_dir }}"
  when: last_sha != current_sha.stdout
  tags:
    - install
    - neovim

- name: "Neovim | Save new build SHA"
  ansible.builtin.copy:
    content: "{{ current_sha.stdout }}"
    dest: "{{ neovim_dir }}/.neovim_build_sha"
    mode: '0644'
  when: last_sha != current_sha.stdout
  tags:
    - install
    - neovim

# If the stable- name: "Neovim | Save current build's HEAD commit SHA"
- name: "Neovim | Plugin Development - Install Luacheck"
  become: true
  shell: "luarocks install luacheck"
  tags:
    - install
    - lua
    - neovim_plugins
