- name: "Neovim | Ubuntu | Install Build Prerequisites"
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
  tags:
    - install
    - neovim

- name: "Neovim | Ubuntu | Install LazyVim Dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fd-find
      - fzf
      - git
      # - lazygit
  tags:
    - install
    - neovim
    - neovim_lazyvim

- name: "Neovim | Ubuntu | Install Plugin Development Dependencies"
  become: true
  ansible.builtin.apt:
    name: luarocks
  tags:
    - install
    - lua
    - neovim
    - neovim_plugins
