- name: "Neovim | {{ ansible_distribution }} | Install Build Prerequisites"
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | LazyVim - Install Prerequisites"
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fd-find
      - git
  tags:
    - neovim_lazyvim

- name: "Neovim | {{ ansible_distribution }} | Plugin Development - Install LuaRocks"
  become: true
  ansible.builtin.apt:
    name: luarocks
  tags:
    - neovim_plugins
    - lua
