- name: "fonts | ensure fonts directory"
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: "fonts | Ensure FiraCode Nerd Font exists"
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/FiraCodeNerdFont*Regular*"
  register: fontfiracode_exists
  ignore_errors: true

- name: "fonts | Download FiraCode Nerd Font"
  when: fontfiracode_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/latest/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
