- name: "fonts | ensure fonts directory"
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

# TODO: Loop for all fonts
- name: "fonts | Ensure Hack Nerd Font exists"
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: yes

# TODO: Github equivalent?
- name: "fonts | Download Hack Nerd Font"
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

# TODO: Loop for all fonts
- name: "fonts | Ensure FiraCode Nerd Font exists"
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/FiraCodeNerdFont*Regular*"
  register: hack_exists
  ignore_errors: yes

# TODO: Github equivalent?
- name: "fonts | Download FiraCode Nerd Font"
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

# TODO: Set font in other roles; move this near top of all.yml; maybe consolidate with system?
